import type { Metadata } from "next";



import Home from "./(home)/home/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function page() {

  return (
      <Home/>
  );
}
