import type { Metadata } from "next";

import { Amplify } from "aws-amplify";

import Home from "./(home)/home/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import awsconfig from "../aws-exports";
Amplify.configure(awsconfig);

export default function page() {
  return (
      <Home />
  );
}